### ISSUE TITLE
Contact Us Page

### ISSUE THREAD

**Issue by Emaslach** [EZ-Street-Asphalt/NOIRCourt#11]
https://noircourt.com/contact/
On the right side under Press: 
North America
[press@ezstreetasphalt.com](mailto:press@ezstreetasphalt.com)
**Change to press@noircourt.com Mail to elyssa@ez.st**

Europe & Middle East
[pressEU@ezstreetasphalt.com](mailto:pressEU@ezstreetasphalt.com)
**Change to pressEU@noircourt.com Mail to elyssa@ez.st**

Australia & Asia
[pressAPAC@ezstreetasphalt.com](mailto:pressAPAC@ezstreetasphalt.com)
**Change to APACpress@noircourt.com Mail to elyssa@ez.st**

Left side: 
Contact

Customer Support
[Visit our Support page](https://www.ezstreetasphalt.com/search/) to find quick answers and learn about EZ Street.

**Please remove for now. We do not have a search page. this can be done in the iteration**

Producing Opportunities
[Learn more](https://www.ezstreetasphalt.com/become-a-producer/) about producing NOIR™ Court
**Please recreate this page on NOIR's website. I don't want this redirecting to EZ Street they are separate companies  **

Distributing Opportunities
[Learn more](https://www.ezstreetasphalt.com/distributor-opportunities/) about becoming an NOIR™ Court distributor
**Please recreate this page on NOIR's website. I don't want this redirecting to EZ Street they are separate companies  **

**Comment by luisezst** [comment]
Done
